var annotated_dup =
[
    [ "Malee", "namespace_malee.html", [
      [ "Editor", "namespace_malee_1_1_editor.html", [
        [ "ReorderableDrawer", "class_malee_1_1_editor_1_1_reorderable_drawer.html", "class_malee_1_1_editor_1_1_reorderable_drawer" ],
        [ "ReorderableList", "class_malee_1_1_editor_1_1_reorderable_list.html", "class_malee_1_1_editor_1_1_reorderable_list" ]
      ] ],
      [ "ReorderableAttribute", "class_malee_1_1_reorderable_attribute.html", "class_malee_1_1_reorderable_attribute" ],
      [ "ReorderableArray", "class_malee_1_1_reorderable_array.html", "class_malee_1_1_reorderable_array" ]
    ] ],
    [ "Map", "namespace_map.html", [
      [ "DottedLineRenderer", "class_map_1_1_dotted_line_renderer.html", "class_map_1_1_dotted_line_renderer" ],
      [ "LineConnection", "class_map_1_1_line_connection.html", "class_map_1_1_line_connection" ],
      [ "Map", "class_map_1_1_map.html", "class_map_1_1_map" ],
      [ "MapConfig", "class_map_1_1_map_config.html", "class_map_1_1_map_config" ],
      [ "MapLayer", "class_map_1_1_map_layer.html", "class_map_1_1_map_layer" ],
      [ "MapManager", "class_map_1_1_map_manager.html", "class_map_1_1_map_manager" ],
      [ "MapNode", "class_map_1_1_map_node.html", "class_map_1_1_map_node" ],
      [ "MapPlayerTracker", "class_map_1_1_map_player_tracker.html", "class_map_1_1_map_player_tracker" ],
      [ "MapView", "class_map_1_1_map_view.html", "class_map_1_1_map_view" ],
      [ "FloatMinMax", "class_map_1_1_float_min_max.html", "class_map_1_1_float_min_max" ],
      [ "IntMinMax", "class_map_1_1_int_min_max.html", "class_map_1_1_int_min_max" ],
      [ "Node", "class_map_1_1_node.html", "class_map_1_1_node" ],
      [ "NodeBlueprint", "class_map_1_1_node_blueprint.html", "class_map_1_1_node_blueprint" ],
      [ "Point", "class_map_1_1_point.html", "class_map_1_1_point" ],
      [ "ExampleEditor", "class_map_1_1_example_editor.html", "class_map_1_1_example_editor" ],
      [ "GameObjectEditor", "class_map_1_1_game_object_editor.html", null ],
      [ "NameOverrideEditor", "class_map_1_1_name_override_editor.html", "class_map_1_1_name_override_editor" ],
      [ "NestedChildDrawer", "class_map_1_1_nested_child_drawer.html", "class_map_1_1_nested_child_drawer" ],
      [ "SurrogateTestEditor", "class_map_1_1_surrogate_test_editor.html", "class_map_1_1_surrogate_test_editor" ],
      [ "Example", "class_map_1_1_example.html", "class_map_1_1_example" ],
      [ "GameObjectExample", "class_map_1_1_game_object_example.html", "class_map_1_1_game_object_example" ],
      [ "NameOverride", "class_map_1_1_name_override.html", "class_map_1_1_name_override" ],
      [ "NestedExample", "class_map_1_1_nested_example.html", "class_map_1_1_nested_example" ],
      [ "RecursionTest", "class_map_1_1_recursion_test.html", null ],
      [ "SurrogateTest", "class_map_1_1_surrogate_test.html", "class_map_1_1_surrogate_test" ],
      [ "ScrollNonUI", "class_map_1_1_scroll_non_u_i.html", "class_map_1_1_scroll_non_u_i" ]
    ] ],
    [ "Answer", "class_answer.html", "class_answer" ],
    [ "AnswerScript", "class_answer_script.html", "class_answer_script" ],
    [ "BackgroundManager", "class_background_manager.html", "class_background_manager" ],
    [ "BossAnsScript", "class_boss_ans_script.html", "class_boss_ans_script" ],
    [ "BossQuizManager", "class_boss_quiz_manager.html", "class_boss_quiz_manager" ],
    [ "CodeVerifier", "class_code_verifier.html", "class_code_verifier" ],
    [ "LeaderboardObject", "class_leaderboard_object.html", "class_leaderboard_object" ],
    [ "LeaderboardResults", "class_leaderboard_results.html", "class_leaderboard_results" ],
    [ "Level", "class_level.html", "class_level" ],
    [ "LoadingScreen", "class_loading_screen.html", "class_loading_screen" ],
    [ "Login", "class_login.html", "class_login" ],
    [ "Notif", "class_notif.html", "class_notif" ],
    [ "Popup", "class_popup.html", "class_popup" ],
    [ "Position", "class_position.html", "class_position" ],
    [ "Question", "class_question.html", "class_question" ],
    [ "QuestionInterface", "class_question_interface.html", "class_question_interface" ],
    [ "QuizManager", "class_quiz_manager.html", "class_quiz_manager" ],
    [ "Result", "class_result.html", "class_result" ],
    [ "SceneChanger", "class_scene_changer.html", "class_scene_changer" ],
    [ "Section", "class_section.html", "class_section" ],
    [ "TextManager", "class_text_manager.html", "class_text_manager" ],
    [ "ToggleTextField", "class_toggle_text_field.html", "class_toggle_text_field" ],
    [ "User", "class_user.html", "class_user" ],
    [ "ViewChallenges", "class_view_challenges.html", "class_view_challenges" ],
    [ "World", "class_world.html", "class_world" ],
    [ "WorldMap", "class_world_map.html", "class_world_map" ]
];